### ISSUE TITLE
Stijlgids Moviematch

### ISSUE THREAD

**Issue by larsvv99** [Alexiatech/Tech-D-groepsopdracht#1]
![Stijlgids](https://user-images.githubusercontent.com/112852815/226909782-be8ae63f-3c16-4c00-9337-2620fe7dc58b.jpg)
Ik heb een algemene stijlgids gemaakt voor ons concept Moviematch

**Comment by MrSmarto** [comment]
Welke font gebruiken we? @larsvv99 misschien kan je deze nog even toevoegen>?
